command_timeout = 10000

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$pijul_channel\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$golang\
$guix_shell\
$lua\
$nim\
$nodejs\
$python\
$ruby\
$rust\
$nix_shell\
$memory_usage\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[cmake]
format = '[$symbol($version)]($style)'

[cmd_duration]
format = '[ ⏱ $duration]($style)'
style = "yellow"

[dart]
format = '[$symbol($version)]($style)'

[deno]
format = '[$symbol($version)]($style)'

[docker_context]
format = '[$symbol$context]($style)'

[fossil_branch]
format = '[$symbol$branch]($style)'

[git_branch]
format = '[$symbol$branch]($style)'
style = "white"

[git_status]
#format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed) ]($style)"
format = ' [(*$conflicted$untracked$modified$staged$renamed$deleted)($ahead_behind$stashed)]($style) '
style = "red"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[golang]
format = '[$symbol($version)]($style)'

[guix_shell]
format = '[$symbol]($style)'

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style)'

[lua]
format = '[$symbol($version)]($style)'

[memory_usage]
format = '$symbol[$ram( | $swap)]($style)'

[nim]
format = '[$symbol($version)]($style)'

[nix_shell]
format = '[$symbol$state( \($name\))]($style)'

[nodejs]
format = '[$symbol($version)]($style)'

[os]
format = '[$symbol]($style)'

[package]
format = '[$symbol$version]($style)'

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'

[red]
format = '[$symbol($version)]($style)'

[ruby]
format = '[$symbol($version)]($style)'

[rust]
format = '[$symbol($version)]($style)'

[sudo]
format = '[as $symbol]($style)'

[time]
format = '[$time]($style)'

[username]
format = '[$user]($style)'

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
